"""Pydantic schemas for API and AI service boundaries."""

from .blueprint import LightBlueprintGenerateRequest, NovelBlueprintDraft
from .consistency import (
    CONSISTENCY_RULE_JSON_SCHEMA,
    DRAFT_CONSISTENCY_REPORT_JSON_SCHEMA,
    ConsistencyDomain,
    ConsistencyIssue,
    ConsistencyIssueLocation,
    ConsistencyRule,
    ConsistencySeverity,
    DraftConsistencyReport,
    consistency_rule_json_schema,
    draft_consistency_report_json_schema,
)
from .draft import (
    DEFAULT_DRAFT_TARGET_WORDS,
    DRAFT_GENERATE_REQUEST_JSON_SCHEMA,
    DRAFT_GENERATE_RESULT_JSON_SCHEMA,
    DraftGenerateRequest,
    DraftGenerateResult,
    draft_generate_request_json_schema,
    draft_generate_result_json_schema,
)
from .outline import (
    CHAPTER_OUTLINE_CONTENT_JSON_SCHEMA,
    CHAPTER_OUTLINE_OPTION_JSON_SCHEMA,
    CHAPTER_OUTLINE_OPTIONS_JSON_SCHEMA,
    ChapterOutlineContent,
    ChapterOutlineDraft,
    ChapterOutlineOptionDraft,
    ChapterOutlineOptionsDraft,
    ConfirmedChapterOutlineDraft,
    chapter_outline_content_json_schema,
    chapter_outline_option_json_schema,
    chapter_outline_options_json_schema,
)
from .review import (
    DRAFT_QUALITY_REVIEW_JSON_SCHEMA,
    DraftQualityReviewReport,
    ReviewIssue,
    ReviewIssueCategory,
    ReviewIssueLocation,
    ReviewSeverity,
    draft_quality_review_json_schema,
)
from .repair import (
    DRAFT_REPAIR_REQUEST_JSON_SCHEMA,
    DRAFT_REPAIR_RESULT_JSON_SCHEMA,
    DraftRepairRequest,
    DraftRepairResult,
    RepairStrategy,
    draft_repair_request_json_schema,
    draft_repair_result_json_schema,
)

__all__ = [
    "CHAPTER_OUTLINE_CONTENT_JSON_SCHEMA",
    "CHAPTER_OUTLINE_OPTION_JSON_SCHEMA",
    "CHAPTER_OUTLINE_OPTIONS_JSON_SCHEMA",
    "CONSISTENCY_RULE_JSON_SCHEMA",
    "DRAFT_CONSISTENCY_REPORT_JSON_SCHEMA",
    "DRAFT_GENERATE_REQUEST_JSON_SCHEMA",
    "DRAFT_GENERATE_RESULT_JSON_SCHEMA",
    "DRAFT_QUALITY_REVIEW_JSON_SCHEMA",
    "DRAFT_REPAIR_REQUEST_JSON_SCHEMA",
    "DRAFT_REPAIR_RESULT_JSON_SCHEMA",
    "DEFAULT_DRAFT_TARGET_WORDS",
    "ChapterOutlineContent",
    "ChapterOutlineDraft",
    "ChapterOutlineOptionDraft",
    "ChapterOutlineOptionsDraft",
    "ConfirmedChapterOutlineDraft",
    "ConsistencyDomain",
    "ConsistencyIssue",
    "ConsistencyIssueLocation",
    "ConsistencyRule",
    "ConsistencySeverity",
    "DraftQualityReviewReport",
    "DraftConsistencyReport",
    "DraftGenerateRequest",
    "DraftGenerateResult",
    "DraftRepairRequest",
    "DraftRepairResult",
    "LightBlueprintGenerateRequest",
    "NovelBlueprintDraft",
    "RepairStrategy",
    "ReviewIssue",
    "ReviewIssueCategory",
    "ReviewIssueLocation",
    "ReviewSeverity",
    "chapter_outline_content_json_schema",
    "chapter_outline_option_json_schema",
    "chapter_outline_options_json_schema",
    "consistency_rule_json_schema",
    "draft_consistency_report_json_schema",
    "draft_generate_request_json_schema",
    "draft_generate_result_json_schema",
    "draft_quality_review_json_schema",
    "draft_repair_request_json_schema",
    "draft_repair_result_json_schema",
]
